### PR TITLE
Added Case Converter

### PR DESCRIPTION
**Pull request by Mridul-2003**
Fixes #(issue)
# Description
I have added a Lowercase and Uppercase Button

Describe your changes in detail

# Screenshots (if appropriate):

Screenshot 2023-01-15 at 11 26 39 AM

### CODE REVIEW

**Comment by Mridul-2003** [comment]
I have made the changes as you have said , I have created this new PR.

**Comment by Mridul-2003** [comment]
Plz go through the code. 
And if any changes required tell me.

**Review by developer-diganta — CHANGES_REQUESTED** [review]
Hi @Mridul-2003! You also have to add the functionality in content.js. The content.js file is the one that controls the webpage. Also please make the PR description in accordance with the template and fill the required details. Feel free to clarify any doubts.

**Comment by Mridul-2003** [comment]
OK I'll add it too

**Comment by Mridul-2003** [comment]
There is no file name content. js. What to do

**Comment by Mridul-2003** [comment]
Oh I found it

**Pull request closed without merging**
