### PR TITLE
Added the workflow,process and aim of the project

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
I have created a section for AIM OF PROJECT,WORKFLOW /PROCESS of project

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
@developer-diganta

**Comment by Bharadwajshivam28** [comment]
@developer-diganta

**Comment by developer-diganta** [comment]
hi @Bharadwajshivam28! You can check the code review. I have mentioned the changes required line wise!

**Comment by Bharadwajshivam28** [comment]
ok sir

**Comment by Bharadwajshivam28** [comment]
sir can you just tag me there i am not able to find it

**Comment by developer-diganta** [comment]
@Bharadwajshivam28 I have tagged you in the review. It starts with `@developer-diganta started a review`. Can you check it once?

**Comment by Bharadwajshivam28** [comment]
ok sir

**Pull request closed without merging**
