### PR TITLE
Added Case Converter

### PR DESCRIPTION
**Pull request by Mridul-2003**
Fixes #(issue)
# Description

Describe your changes in detail

I have added case converter section which includes lowercase and uppercase button.
I have use text-transform property in javascript for uppercase and lowercase.
# Screenshots (if appropriate):
Screenshot 2023-01-16 at 1 38 10 PM

I have added changes in content.js file also as you had said ....

### CODE REVIEW

**Review by developer-diganta — CHANGES_REQUESTED** [review]
You can simply add the listener in content.js inside the preexisiting if-else cases. Also can you check once for to uppercase. It seems to remove all css. Also please update your description as per the format. The issue number and the last declaration is required.
dino

**Comment by Mridul-2003** [comment]
OK I'll do the changes

**Comment by Mridul-2003** [comment]
OK I change it to css text transform property give me just 1 day, I'll do it soon...

**Review by Mridul-2003 — COMMENTED** [review]
Hello, I have made the changes you have requested from me....

**Comment by Mridul-2003** [comment]
Plz review the changes

**Comment by Mridul-2003** [comment]
Ok

**Review by Mridul-2003 — COMMENTED** [review]
I have done the changes you requested plz review them

**Review by Mridul-2003 — COMMENTED** [review]
I have done the changes you have requested plz review them

**Comment by Mridul-2003** [comment]
How I get scores in SWOC for this contribution....

**Comment by developer-diganta** [comment]
> How I get scores in SWOC for this contribution....

Once your PR is merged, you will get a score according to the level of the issue you solve. In the issue, you can see the labels : 
Beginner - 10 points
Intermediate - 20 points
Advance - 30 points

**Review by Mridul-2003 — COMMENTED** [review]
I have made the changes that you have said plz review them....

**Review by Mridul-2003 — COMMENTED** [review]
Plz merge this PR I have made the required changes.

https://user-images.githubusercontent.com/110475111/213668643-4e62057e-bc01-4b12-a9ea-b06c605778dd.mov

**Comment by Mridul-2003** [comment]
Thanks to guide me

**Review by developer-diganta — CHANGES_REQUESTED** [review]
Hi @Mridul-2003 ! Can you please pull the changes since in your PR a quite a few functionalities are missing. Also resolve the merge conflicts (should happen when you get the latest files). And please update the PR description with the template.

**Pull request closed without merging**
