### PR TITLE
Added custom scrollbar

### PR DESCRIPTION
**Pull request by daredevil3435**
#7 is resolved. Do let me know if there're any more modification required.

### CODE REVIEW

**Comment by Durgesh4993** [comment]
**After Code apply** -

30 12 2022_19 02 48_REC


**Before Code apply** -
30 12 2022_19 06 16_REC

**Review by developer-diganta — APPROVED** [review]

**Comment by developer-diganta** [comment]
Thank You for your contribution

**Comment by developer-diganta** [comment]
@daredevil3435 can you please tell your name so that I can fill the score sheet of SWOC?

**Comment by daredevil3435** [comment]
> @daredevil3435 can you please tell your name so that I can fill the score sheet of SWOC?

yes, kanak umrani

**Comment by daredevil3435** [comment]
I have my exams this month, is it fine if I start contributing again after my exams are over?

**Comment by developer-diganta** [comment]
Yeah sure! Concentrate on your exams first. All the best!

**Pull request merged**
