### PR TITLE
 Add Dark Mode in a extensions

### PR DESCRIPTION
**Pull request by Sumit9953**
I have Added Dark mode in a extension. Kindly look into that and feel free to give any suggestions. Thank You!
image

### CODE REVIEW

**Comment by Sumit9953** [comment]
@developer-diganta  Look at this 

image

**Comment by developer-diganta** [comment]
Looks good. Just change the font color to white

**Comment by Sumit9953** [comment]
@developer-diganta Done , check PR

**Review by developer-diganta — CHANGES_REQUESTED** [review]
@Sumit9953 This looks great but there is one problem. I see you have used font awesome, but for security reasons, extensions don't usually allow cross site data/scripts to be added. I guess we can do that by adding it to manifest.json but I believe since our extension is directly working with the main web page, it would be a security risk to allow it. 
You can take inspiration from this : w3schools.com/howto/howto_css_switch.asp
or you are free to make it in whatever way you want!

**Comment by Sumit9953** [comment]
I remove font awesome , can you look at this changes and give suggestion look good or Not

image

**Review by developer-diganta — CHANGES_REQUESTED** [review]
@Sumit9953 There is just one more change that is required. You directly cannot add eventlisteners to the popup.html file. Instead you have to use the js file to add it. Just do that and check if it works and then it should be good.

**Comment by Sumit9953** [comment]
@developer-diganta  Done

**Review by developer-diganta — CHANGES_REQUESTED** [review]
Hi @Sumit9953 ! What I was saying is remove onclick from popup.html. And add that onclick using js. So in background.js do something like this:
```
document.getElementById('checkbox').addEventListener('click',()=>myFunction())

function myFunction() {
  var element = document.body;
  element.classList.toggle("dark-mode");
}
```
Also just change the name of myFunction to something more semantic. Then just try it and see if it works. You can right click on the extension, once opened and get the dev tools for it.
And one more thing, just don't add the .vscode folder.

**Comment by Sumit9953** [comment]
@developer-diganta Done I remove onClick function from the HTML , look the changes and merge the pr

**Pull request merged**
