### PR TITLE
added following font style :- Georgia, Times New Roman , monaco,helve…

### PR DESCRIPTION
**Pull request by Nehaaa3121**
…tica & Font size : 12px

### CODE REVIEW

**Comment by Nehaaa3121** [comment]
> Can you please check for Monaco and Georgia. Those two are not working. Maybe you have to externally import them.

Now please check:)

**Review by developer-diganta — CHANGES_REQUESTED** [review]
You have to also add the font in the [content.js](https://github.com/developer-diganta/Dino/blob/main/webpage-assets/js/content.js#L29) file! I guess that would make it work fine. Just make this change! Other than that good work!

**Comment by Nehaaa3121** [comment]
> You have to also add the font in the [content.js](https://github.com/developer-diganta/Dino/blob/main/webpage-assets/js/content.js#L29) file! I guess that would make it work fine. Just make this change! Other than that good work!

Done!!!

**Comment by developer-diganta** [comment]
Can you please resolve the merge conflict?

**Review by developer-diganta — APPROVED** [review]
LGTM

**Comment by developer-diganta** [comment]
Thank you for the PR! Merged!

**Comment by developer-diganta** [comment]
Hi @Nehaaa3121 ! Can I get your name please. We have to include it in the scoresheet for SWOC

**Comment by Nehaaa3121** [comment]
Hello. Myself  Neha Choudhary.

**Pull request merged**
