### PR TITLE
Screenshots added for Issue #2

### PR DESCRIPTION
**Pull request by Ujwal19k**
Here I have added the screenshots of the UI which I have created using figma.

### CODE REVIEW

**Comment by developer-diganta** [comment]
Looks great @Ujwal19k! Thanks! Just one thing, instead of giving the screenshots of readme (Installation etc), I recommend putting actual text. That after all is much more accessible.

**Comment by Ujwal19k** [comment]
> Looks great @Ujwal19k! Thanks! Just one thing, instead of giving the screenshots of readme (Installation etc), I recommend putting actual text. That after all is much more accessible.
Yes I will improve that UI. I have added ss for now just to get an idea.

**Comment by developer-diganta** [comment]
@Ujwal19k I'll be merging this one then? For any subsequent change/idea make a new issue and a PR for that.

**Comment by Ujwal19k** [comment]
> @Ujwal19k I'll be merging this one then? For any subsequent change/idea make a new issue and a PR for that.

Yes. I am working on few changes

**Comment by Ujwal19k** [comment]
> > @Ujwal19k I'll be merging this one then? For any subsequent change/idea make a new issue and a PR for that.
> 
> Yes. I am working on few changes

within 2 days

**Comment by developer-diganta** [comment]
Alright, cool. I am merging this one. Make a new issue first and then make a PR for that one then.

**Review by developer-diganta — APPROVED** [review]
LGTM

**Comment by ManavLohia945** [comment]
Ok great.. Now are you creating a new issue for the coding part tagging this issue?

**Comment by ManavLohia945** [comment]
So that I can start coding for the website

**Comment by developer-diganta** [comment]
Yup...just a sec. Also @ManavLohia945 do not worry much about optimized code, all designs etc. Just give atleast a simple website. We can change the features with more PRs. Also comment on the issue. I'll assign you

**Pull request merged**
