### PR TITLE
put 3 buttons of font style per row

### PR DESCRIPTION
**Pull request by Harikaraja**
issue number :  #123

### CODE REVIEW

**Review by developer-diganta — CHANGES_REQUESTED** [review]
image
The font style buttons still overflow. I would suggest using flexbox or grid layout to make sure overflow does not happen. Also please update the PR description using the template provided. It is essential to get your score. And please remove the .vscode from your PR. Do ask if  you have any doubts.

**Comment by Harikaraja** [comment]
Good afternoon sir,

Are you saying that all the buttons must be aligned in a single row.

**Comment by developer-diganta** [comment]
No, it should be 3 per row. But if you see the screenshot, the 3rd buttons are not visible completely. That's why I suggested flex-box or grid, then you don't have to worry about hardcoding size values.

**Comment by Harikaraja** [comment]
Sir actually in my laptop screen i am able to see all the buttons clearly
.can you tell me the screen width you are viewing so that I can look into
that

**Comment by developer-diganta** [comment]
Yup that is the problem I am saying. It won't be possible for you to make sure you hardcode it for every screen width. Try using %s to make sure you get it. My resolution is 1920 X 1080.

**Comment by Harikaraja** [comment]
Ok sir

**Pull request closed without merging**
