### PR TITLE
Changed UI of Dino.

### PR DESCRIPTION
**Pull request by CHEEMS-1206**
Greeting readers !

issue #53 
Upon forking the project, the very first thing that came to mind was the UI and the styling. I have tried my best to make it a bit attractive, hoping that it will be merged along to the legacy code. And I have added the functionality of dark mode option in the project.

### CODE REVIEW

**Comment by developer-diganta** [comment]
Thank You for the PR. The main design of the website has to be kept really simple. You can keep this as a dark mode option if you want.

**Comment by CHEEMS-1206** [comment]
shalln't I just change the bg-colors of the site .....
may be than it could be worth of a merge.

> Thank You for the PR. The main design of the website has to be kept really simple. You can keep this as a dark mode option if you want.

**Comment by CHEEMS-1206** [comment]
coz I have made it a bit more responsive than earlier as well.
and if not than do guide me, what else I can do .....

**Comment by developer-diganta** [comment]
We can see responsive later on as this is a chrome extension, we can safely assume certain width and heigh(since mobile devices are not involved). In the mean time, you can see a bit more friendly dyslexic color scheme for dark mode and add it!

**Comment by developer-diganta** [comment]
Also please raise an issue so that I can assign you

**Comment by CHEEMS-1206** [comment]
> Also please raise an issue so that I can assign you

I have raised an issue (issue #53 ) as well as, have submitted the PR maybe it is worth a merge now.
Even if not, tell me what else I can do.

**Comment by developer-diganta** [comment]
@CHEEMS-1206 Thank you for investing your time. Can you do one thing, for this pr don't change any responsiveness. Instead you can use  a dark mode color scheme with black/yellow. Some else is also working on another color scheme, so we can keep as many schemes as possible.

**Comment by CHEEMS-1206** [comment]
@developer-diganta , I have made the changes as guided. Do look over it and guide if anything else could be done.

**Comment by CHEEMS-1206** [comment]
I have also resolved any conflicts present.
what's the next step I can do.

**Comment by CHEEMS-1206** [comment]
@developer-diganta do guide me what could be done next ...
please

**Comment by developer-diganta** [comment]
Thank You @CHEEMS-1206 ! Sorry I guess there was some confusion. It would be great if you can just change the background colour of the extension to black and make the colour of font yellow. And I would suggest do not add the responsiveness.
image
If you feel this PR is getting cluttered, you can open a new PR. If you have any other doubts do clarify!
You can also do one thing, in this PR simply add the colours scheme to css. In another PR, you can link the schemes (open an issue for that)

**Pull request closed without merging**
