### PR TITLE
A way to add any font to the webpage

### PR DESCRIPTION
**Pull request by BhagatHarsh**
So I started by working on this issue of adding new fonts #29 but as someone is already working on adding a specific font I directed my focus on adding any font they like from now on.

So what I have done is I googled and found this [link](https://developer.chrome.com/docs/extensions/mv3/manifest/web_accessible_resources/) from which i was able to add our assets folder to the webpage (exposing the folder via manifest.json) and now we can just add the new font in the assets/fonts folder and add a new ```@font-face``` in the webpage-assets/css/styles.css to be able to access it anywhere in the webpage.

### CODE REVIEW

**Comment by BhagatHarsh** [comment]
In this PR I also tested that the fonts are working by adding the Calibre font which was not working before.
and tried Times New Roman and Georgia as well.

**Comment by developer-diganta** [comment]
Can you remove the .DS_Store file as that has no role. Apart from that everything is great! Thank You!

**Review by developer-diganta — CHANGES_REQUESTED** [review]
Can you remove the .DS_Store file as that has no role. Apart from that everything is great! Thank You!

**Review by developer-diganta — APPROVED** [review]
LGTM

**Comment by developer-diganta** [comment]
Thank You for the PR

**Pull request merged**
