### PR TITLE
Add a translate option for text on web pages

### PR DESCRIPTION
**Pull request by Durgesh4993**

### CODE REVIEW

**Comment by Durgesh4993** [comment]
image


image

**Review by developer-diganta — CHANGES_REQUESTED** [review]
Hey good job! Just do one thing, no need to have that click me button. The button where you have added the description, make that a click me.

**Comment by Durgesh4993** [comment]
ok sir

**Review by developer-diganta — CHANGES_REQUESTED** [review]
Hey @Durgesh4993 ! Just wrap the button within the a tag and I think it should be good

**Comment by Durgesh4993** [comment]
yes sir

**Comment by Durgesh4993** [comment]
@developer-diganta now it's complete, any other work for me

**Review by developer-diganta — CHANGES_REQUESTED** [review]
Hi @Durgesh4993 . What I was saying was make it something like this `<a href=''..'><button>Click here to translate anything</button></a>`
Also do resolve the merge conflicts

**Comment by Durgesh4993** [comment]
ok sir now please check it is right or not, thank you for help

**Review by developer-diganta — APPROVED** [review]
LGTM. Thank You for the PR. Merged.

**Pull request merged**
