### PR TITLE
Add font style Opensans

### LINKED ISSUE #91: Add font style open sans
I want to add open sans in font style.

### PR DESCRIPTION
**Pull request by suvamita**
Fixes #91
# Description
Add OpenSans font style.

# Screenshots:
image

# Types of changes
- [x] New feature (non-breaking change which adds functionality)

# Checklist:
- [x] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.

# SWOC Participation
- Name: Suvamita Sadhukhan
- Discord Username: suvamita_14
- [x] I have included the issue number in my PR

### CODE REVIEW

**Review by developer-diganta — CHANGES_REQUESTED** [review]
Hi @suvamita !  Can you please check `popup.html` file once. In your PR, quite a few features are getting removed.  Just correct it and the PR should be good to merge.

**Comment by suvamita** [comment]
Can you please check popup.html correct or not?

**Review by developer-diganta — CHANGES_REQUESTED** [review]
Hi @suvamita! Yes popup.html is fine now. But had a doubt. Why have you used `|| request.fontStyle === "OpenSans-Regular"` on line 26 of content.js. Won't it then everytime change text to Trebuchet MS?

**Comment by suvamita** [comment]
@developer-diganta while trying to change content.js, I made a mistake on line 26 of content.js. Sorry, I didn't check it properly.

**Review by developer-diganta — APPROVED** [review]
Cool. No issues @suvamita! Thanks for the PR. Merged.

**Pull request merged**
