### PR TITLE
Added new Issue_Templates

### PR DESCRIPTION
**Pull request by SattyamSamania**
I have Added 2 new Issue Templates. Kindly look into that and feel free to give any suggestions. Thank You!

### CODE REVIEW

**Review by developer-diganta — COMMENTED** [review]
Looks good! Can you also add 1 more with blank issue?

**Comment by SattyamSamania** [comment]
> Looks good! Can you also add 1 more with blank issue?

@developer-diganta means I add another file with only issue section?

**Comment by developer-diganta** [comment]
Extremely sorry @SattyamSamania ! I missed your comment. Yes, just add another file

**Comment by SattyamSamania** [comment]
> Extremely sorry @SattyamSamania ! I missed your comment. Yes, just add another file

@developer-diganta I will add tomorrow another file with only one question like Describe your issue. Is that OK?

**Comment by developer-diganta** [comment]
Sounds good!

**Comment by SattyamSamania** [comment]
Hey @developer-diganta I am making another PR with the three files as suggested by you.

**Pull request closed without merging**
