### PR TITLE
added revert font color button

### PR DESCRIPTION
**Pull request by Nehaaa3121**

### CODE REVIEW

**Review by developer-diganta — CHANGES_REQUESTED** [review]
Thank You for the PR! But there is one problem. You also have to change the font colour from content.js . For reference, you can check how background color reversal has been done. Do not hesitate to ask any doubts if you have!

**Review by developer-diganta — CHANGES_REQUESTED** [review]
@Nehaaa3121 I think you have to change the property name to just color in setProperty. Also I guess you can use ```all``` to reverse the font colors since all already has the required tags selected.

**Comment by Nehaaa3121** [comment]
@developer-diganta now please check.

**Comment by Nehaaa3121** [comment]
@developer-diganta please check

**Comment by Nehaaa3121** [comment]
@developer-diganta

**Review by developer-diganta — CHANGES_REQUESTED** [review]
Just add this in content.js in line 142 to 144 and this should be good.
```        
        const all = document.getElementsByTagName("*")[0];
            all.style.setProperty("color", fontColor);
```

**Comment by Nehaaa3121** [comment]
@developer-diganta

**Review by developer-diganta — APPROVED** [review]
LGTM. Thanks for the PR. Merged. Also @Nehaaa3121 please update the PR description with the template. Helps me keep the scores updated!

**Pull request merged**
