### PR TITLE
 Added English dictionary 

### PR DESCRIPTION
**Pull request by vijay-kumar-yadav**
[I have added english dictionary, user have to first select text on any webpage then click on get definition in extension popup.

### CODE REVIEW

**Comment by developer-diganta** [comment]
@vijay-kumar-yadav I could not figure out how to select the text from a page. How have you implemented the selecting of a word?

**Comment by vijay-kumar-yadav** [comment]
> @vijay-kumar-yadav I could not figure out how to select the text from a page. How have you implemented the selecting of a word?
like this--->
image

**Comment by developer-diganta** [comment]
Cool enough! I think selecting a word directly won't be a viable option since extension would stop working on mouse click on page. Can you simply keep an input field which takes a word and gives the meaning? Also, can you add this at the bottom?

**Comment by vijay-kumar-yadav** [comment]
> Cool enough! I think selecting a word directly won't be a viable option since extension would stop working on mouse click on page. Can you simply keep an input field which takes a word and gives the meaning? Also, can you add this at the bottom?

okay that will be easy I will update it.

**Comment by vijay-kumar-yadav** [comment]
> > Cool enough! I think selecting a word directly won't be a viable option since extension would stop working on mouse click on page. Can you simply keep an input field which takes a word and gives the meaning? Also, can you add this at the bottom?
> 
> okay that will be easy I will update it.

also extension will not stop working as when you first select a text and then go to the extension click on the get definition option it will show output and next time you will go there it will load fresh.

you can also check it here [https://github.com/vijay-kumar-yadav/Dino](url) by cloning.

**Comment by vijay-kumar-yadav** [comment]
> I tried that but I did not receive the output. image It was not able to get the word. I guess we can avoid this, what do you think?

don't run it on live server run it as extension then there will be no error..

**Comment by developer-diganta** [comment]
Cool enough, it is working. I guess you can keep it that way for now. No need to add input parameter! Great Job! I'll merge it once we receive the guidelines for points and all!

**Comment by vijay-kumar-yadav** [comment]
> Cool enough, it is working. I guess you can keep it that way for now. No need to add input parameter! Great Job! I'll merge it once we receive the guidelines for points and all!

ok Thank you !

**Comment by developer-diganta** [comment]
> > I tried that but I did not receive the output. image It was not able to get the word. I guess we can avoid this, what do you think?
> 
> don't run it on live server run it as extension then there will be no error..

I guess my connection was slow 😅

**Comment by vijay-kumar-yadav** [comment]
> > > I tried that but I did not receive the output. image It was not able to get the word. I guess we can avoid this, what do you think?
> > 
> > 
> > don't run it on live server run it as extension then there will be no error..
> 
> I guess my connection was slow 😅.. website did not load properly

Yeah that could be the reason.

**Comment by developer-diganta** [comment]
@vijay-kumar-yadav Can you resolve the merge conflicts. I can then merge the PR. Thanks

**Comment by vijay-kumar-yadav** [comment]
> @vijay-kumar-yadav Can you resolve the merge conflicts. I can then merge the PR. Thanks

@developer-diganta fixing now

**Comment by vijay-kumar-yadav** [comment]
> > @vijay-kumar-yadav Can you resolve the merge conflicts. I can then merge the PR. Thanks
> 
> @developer-diganta fixing now

@developer-diganta  to fix this I have to first close this pr and open new pr please merge new pr asap!

**Comment by developer-diganta** [comment]
@vijay-kumar-yadav You can do it in this PR itself. Since it won't be a huge chunk of code, you can use github's web editor to resolve the conflicts.

**Comment by vijay-kumar-yadav** [comment]
> @vijay-kumar-yadav You can do it in this PR itself. Since it won't be a huge chunk of code, you can use github's web editor to resolve the conflicts.

actually resolving in vs code is quite easy thats why I preferred that:
image

**Comment by developer-diganta** [comment]
Cool. No issues

**Pull request closed without merging**
