### PR TITLE
Added Tahoma Font issue#95

### PR DESCRIPTION
**Pull request by officialarmannqureshi**
Fixes #(issue)
issue #95 . I have Tahoma font in web page font style and made some changes in content js and popup file.

Describe your changes in detail
We have added new feature of the Tahoma font style which is the best font style for those who are suffering from dyslexia.

# Screenshots (if appropriate):
image
image

# Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist:

- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

# SWOC Participation

- Name: Mohammad Nazim Qureshi
- Discord Username: atoz #5954
- [X] I have included the issue number in my PR

### CODE REVIEW

**Comment by officialarmannqureshi** [comment]
Thank you for giving me an opportunity to do a contribution to your project.
Kindly merge it asap.

**Review by developer-diganta — CHANGES_REQUESTED** [review]
Hi @officialarmannqureshi ! You also have to add the eventListener using background.js. You can refer to the other fontstyles in background.js. If you have any doubt, do ask me

**Comment by officialarmannqureshi** [comment]
> Hi @officialarmannqureshi ! You also have to add the eventListener using background.js. You can refer to the other fontstyles in background.js. If you have any doubt, do ask me

I think it's there and its working great

**Comment by developer-diganta** [comment]
@officialarmannqureshi see I tried it. It won't work since the flow is as such: the onlick eventListener is added via background.js. Upon onclick, the background.js will send the message (the action) to content.js to make the change to the webpage.
dino

**Comment by developer-diganta** [comment]
Sorry! My bad! there was an error on my system. Thanks for the PR! Merged!

**Review by developer-diganta — APPROVED** [review]

**Comment by officialarmannqureshi** [comment]
is it marked as SWOC?

**Comment by developer-diganta** [comment]
Yes

**Pull request merged**
