### PR TITLE
Center buttons in preference section

### LINKED ISSUE #101: Center the buttons in Your Preferences section
### Subject of the issue
Center the buttons in the your preferences center.
image
You can refer  to issue #100 to see the required widths.

### PR DESCRIPTION
**Pull request by Sanya2911**
Fixes #101

Description
I have centered the buttons in image sections.

Screenshots (if appropriate):
DINO

Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

SWOC Participation
- Name: Sanya Saeed
- Discord Username: sanya29#3771
- [X] I have included the issue number in my PR

### CODE REVIEW

**Comment by Sanya2911** [comment]
What is the issue . please guide...

**Review by developer-diganta — CHANGES_REQUESTED** [review]
Hi @Sanya2911 ! As mentioned in the other PR, just remove the media queries and directly add the styles!

**Comment by Sanya2911** [comment]
please check this now, I have removed media queries .

**Review by developer-diganta — CHANGES_REQUESTED** [review]
Hi @Sanya2911 ! You seemed to have deleted the background.js file. Just revert that and make sure you only add styles and popup.html and not the background.js file. You can do this in a fresh PR if you want

**Comment by Sanya2911** [comment]
so should I close this pull request ??

**Comment by developer-diganta** [comment]
Yup you can close this one and make a new request with the html and css files. Also make sure to resolve the merge conflict.

**Pull request closed without merging**
